add_executable(sgemm0 sgemm0.cu)
add_executable(sgemm1 sgemm1.cu)
add_executable(sgemm2 sgemm2.cu)
add_executable(sgemm3 sgemm3.cu)
add_executable(sgemm4 sgemm4.cu)

target_link_libraries(sgemm0 PRIVATE CUDA::cublas)
target_link_libraries(sgemm1 PRIVATE CUDA::cublas)
target_link_libraries(sgemm2 PRIVATE CUDA::cublas)
target_link_libraries(sgemm3 PRIVATE CUDA::cublas)
target_link_libraries(sgemm4 PRIVATE CUDA::cublas)
